sudo: required
services:
  - docker

before_install:
  - docker build -t cauldyclark15/docker-react .

script:
  - docker run cauldyclark15/docker-react npm run test -- --coverage

deploy:
  provider: gae
  keyfile: client_key.json
  project: kubernetes-fiddle-trial
  on:
    branch: master
